version: '3'
services:
#  api:
#    build:
#      context: ./backend
#      dockerfile: Dockerfile
#    volumes:
#      - ./backend/app-api-todo:/go/src/app
#    ports:
#      - "8080:8080"
#    stdin_open: true
#    depends_on:
#      - "mysql"
  mysql:
    image: mysql:5.7.22
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: todo
    container_name: mysql-container
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    ports:
      - "3307:3307" # host:container_port
    command: --port 3307
